# Site settings
title: "AI Bootcamp: From RAG to Agents"
description: "Master AI systems from Retrieval-Augmented Generation to intelligent agents in this comprehensive hands-on course"
baseurl: ""
url: "https://alexeygrigorev.github.io/aihero"

# Build settings
markdown: kramdown
highlighter: rouge

# Site configuration
author: "Alexey Grigorev"
email: "alexey@datatalks.club"
twitter_username: "AlexeyGrigorev"
github_username: "alexeygrigorev"

# SEO and social sharing
image: "/images/logo.png"  # Default social preview image
logo: "/images/logo.png"   # Site logo (used by jekyll-seo-tag)
social:
  name: "Alexey Grigorev"
  links:
    - "https://twitter.com/AlexeyGrigorev"
    - "https://github.com/alexeygrigorev"
twitter:
  username: "AlexeyGrigorev"
  card: summary_large_image
lang: en_US
favicon: "/images/favicon.png"             # Site favicon

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: :always

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md
  - assets/README.md
  - "*.log"
  - .git/
  - .gitignore

# Performance optimizations
incremental: true
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false